<a href="https://colab.research.google.com/github/GITJAYSONI/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# #introduction to numpy
# numpy is an open source library that is used for scientific calculation

# why numpy is better that list
# 1 list is hetrogenous data type and numpy has homogenous data type
# 2 list take more memory as compare to numpy
# 3 list take more time executionn as compare to numpy

In [2]:
# pip install numpy

In [3]:
import numpy as np

In [4]:
a=[1,45,90]
type(a)

list

In [6]:
b=np.array(a)
b

array([ 1, 45, 90])

In [7]:
type(b)

numpy.ndarray

In [8]:
#how can we create a user-defiend array

In [ ]:
a=[]
size=int(input("enter the size of array"))
for i in range(size):
    val=int(input("enter the value"))
    a.append(val)
#print(a)


In [ ]:
type(b)

In [9]:
# how can we check shape,size and dimension of an arry

In [10]:
a=[[1,2,3,0],[4,5,6,7],[7,8,9,3]]
b=np.array(a)
b

array([[1, 2, 3, 0],
       [4, 5, 6, 7],
       [7, 8, 9, 3]])

In [11]:
print("total shape=",b.shape)

total shape= (3, 4)


In [12]:
print("total size=",b.size)

total size= 12


In [13]:
print("total dimension=",b.ndim)

total dimension= 2


In [14]:
#pre-defined function in numpy

In [15]:
# (1).zero () ---> it will return an arry in which all the value will be 0 in
# either one-dimensional or multi-dimensional array

In [16]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [17]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
print("total shape=",a.shape)
print("total elememt=",a.size)

total shape= (3,)
total elememt= 3


In [19]:
print("total shape=",b.shape)
print("total elememt=",b.size)

total shape= (3, 3)
total elememt= 9
